### ISSUE TITLE
[BUG]: Dynamic require of "path" is not supported

### ISSUE THREAD

**Issue by sergey-s-betke** [IT-Service-NPM/gulp-file2qr#2]
### Current behavior

Error:
Dynamic require of "path" is not supported

### Expected behavior

Gulp must start without error.

### Package version

v1.1.0

### Node version

v23.3.0

### Relevant log output

```shell
npx gulp build:images:URL-QRCodes
(node:21656) ExperimentalWarning: CommonJS module C:\Program Files\nodejs\node_modules\npm\node_modules\debug\src\node.js is loading ES Module C:\Program Files\nodejs\node_modules\npm\node_modules\supports-color\index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18816) ExperimentalWarning: CommonJS module C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\gulp-cli\lib\shared\require-or-import.js is loading ES Module C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\gulpfile.mjs using require().  
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Dynamic require of "path" is not supported
    at file:///C:/Users/Sergei.S.Betke.W00854/Documents/csm.ivanovo.ru/DocTemplates/node_modules/gulp-file2qr/dist/index.js:11:9
    at node_modules/vinyl/index.js (file:///C:/Users/Sergei.S.Betke.W00854/Documents/csm.ivanovo.ru/DocTemplates/node_modules/gulp-file2qr/dist/index.js:1616:16)
    at __require2 (file:///C:/Users/Sergei.S.Betke.W00854/Documents/csm.ivanovo.ru/DocTemplates/node_modules/gulp-file2qr/dist/index.js:14:50)     
    at file:///C:/Users/Sergei.S.Betke.W00854/Documents/csm.ivanovo.ru/DocTemplates/node_modules/gulp-file2qr/dist/index.js:1898:29
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:395:35)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
    at loadESMFromCJS (node:internal/modules/cjs/loader:1376:24)
    at Module._compile (node:internal/modules/cjs/loader:1528:5)
    at Object..js (node:internal/modules/cjs/loader:1698:10)
    at Module.load (node:internal/modules/cjs/loader:1303:32)
    at Function._load (node:internal/modules/cjs/loader:1117:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1325:12)
    at require (node:internal/modules/helpers:136:16)
    at requireOrImport (C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\gulp-cli\lib\shared\require-or-import.js:20:11)
    at execute (C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\gulp-cli\lib\versioned\^5.0.0\index.js:35:3)     
    at onExecute (C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\gulp-cli\index.js:230:24)
    at Liftoff.<anonymous> (C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\gulp-cli\index.js:153:5)
    at Liftoff.execute (C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\liftoff\index.js:320:14)
    at module.exports (C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\flagged-respawn\index.js:52:3)
    at Liftoff.<anonymous> (C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\liftoff\index.js:310:7)
    at C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\liftoff\index.js:265:9
    at C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\v8flags\index.js:138:14
    at C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\v8flags\index.js:47:14
    at C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates\node_modules\v8flags\index.js:59:7
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
PS C:\Users\Sergei.S.Betke.W00854\Documents\csm.ivanovo.ru\DocTemplates>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sergey-s-betke** [comment]
В index.js упаковывается много кода из других модулей. Нам это не требуется вообще. В частности:

```javascript
// node_modules/replace-ext/index.js
var require_replace_ext = __commonJS({
  "node_modules/replace-ext/index.js"(exports, module) {
    "use strict";
    var path = __require("path");
    function replaceExt(npath, ext) {
      if (typeof npath !== "string") {
        return npath;
      }
      if (npath.length === 0) {
        return npath;
      }
      var nFileName = path.basename(npath, path.extname(npath)) + ext;
      var nFilepath = path.join(path.dirname(npath), nFileName);
      if (startsWithSingleDot(npath)) {
        return "." + path.sep + nFilepath;
      }
      return nFilepath;
    }
    function startsWithSingleDot(fpath) {
      var first2chars = fpath.slice(0, 2);
      return first2chars === "." + path.sep || first2chars === "./";
    }
    module.exports = replaceExt;
  }
});
```
